apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
  labels:
    app: keycloak
data:
  KEYCLOAK_IMPORT: /import/realm-export.json #-Dkeycloak.profile.feature.upload_scripts=enabled
  DB_VENDOR: POSTGRES
  DB_ADDR: postgres
  DB_DATABASE: som_core_db
  DB_USER: postgres
  DB_SCHEMA: keycloak
  DB_PASSWORD: 123qwe
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: 123qwe
