[tool.poetry]
name = "simple_poll_pytests"
version = "0.1.0"
description = "pytests for simplePoll app"
authors = ["h0110w"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
